### ISSUE TITLE
Looking for help, with making a button a link

### ISSUE THREAD

**Issue by siddharthchatterjee** [siddharthchatterjee/Profile-Project#1]
@jordanmccullough: this is a link to my gist from CodePen, if you have some time please look at it and let me know how to make my buttons act as a hyperlink. Thanks 😃 🚗 🌆 🐶 🐶 

<script src="https://gist.github.com/anonymous/438b0dc9728573ac7f6c0436a05fd4a8.js"></script>

cc: @bonniec

**Comment by siddharthchatterjee** [comment]
https://gist.github.com/anonymous/438b0dc9728573ac7f6c0436a05fd4a8

Here is the link to my gist. Thank you!

**Comment by jordanmccullough** [comment]
Hi, @siddharthchatterjee. Thanks for the invite.

Let me give you just two hints, and then see if you can make all those buttons work on your web page. :smile:

**Tip 1**
Your web page needs to "know" about that awesome CSS file you have put together. The way you include your CSS in your web page would be with this line in the HTML file:

```
<link  href="style.css" rel="stylesheet" />
```

**Tip 2**
HTML "buttons" are typically used for sending information on web sites, like when you sign-in to your GitHub account or you log into your school's web site for example.

Instead of a button, you can keep the links as simple as possible by using your CSS `btn` class on just the `<a>` like this:

```
<a class="btn btn-success"  href="yourlinkaddress">Link Title</a>
```

Give those tips a try, and your buttons should look like this:

<img width="153" alt="screenshot 2016-10-13 21 26 12" src="https://cloud.githubusercontent.com/assets/352082/19374792/c4133de0-918b-11e6-8ebf-88493a5e4023.png">

Happy coding and have fun! Let me know how these edits go and if I can help with anything else.

/cc @BonnieC

**Comment by siddharthchatterjee** [comment]
@jordanmccullough  Thanks for helping me with my website. However, the problem was not with the code, but with the editor, CodePen. CodePen does not allow external links, however you can get around this problem by adding "target='_blank'. 😃 🐶 🐶 🐶 🐶

**Comment by jordanmccullough** [comment]
@siddharthchatterjee, Great! Glad you solved it. 

Let me know if I can help with anything else, but sounds like you're on the right path now.
